# Generated by Django 2.1.7 on 2019-02-13 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0002_auto_20190213_0138'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='option_one',
            field=models.CharField(default='None provided', max_length=140),
        ),
        migrations.AddField(
            model_name='question',
            name='user',
            field=models.ManyToManyField(through='quickstart.Answer', to='quickstart.User'),
        ),
        migrations.AlterField(
            model_name='question',
            name='author',
            field=models.CharField(max_length=30),
        ),
    ]
